apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-build-dev
  labels:
    version: "1.0.0"
    environment: dev
    type: build
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: develop
    - name: image-name
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.image-name):dev
