apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: alternative-source
  namespace: default
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/spring-projects/spring-petclinic.git
