apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-service-account
  namespace: multi-stage-pipeline-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-service-account-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline-service-account
  namespace: multi-stage-pipeline-lab
